#!/usr/bin/env bash
# Build a self-contained dough AppImage from the PyInstaller onedir.
# GENERATED by `dough bake` — edit the template
# (packaging/templates/appimage/build_appimage.sh.j2), never this file.
#
# Build on the OLDEST supported base (Ubuntu 22.04, glibc 2.35 — the PySide6
# manylinux floor) so the result runs FORWARD onto every newer distro. AppImage
# gives forward compatibility only: built against glibc X runs on >= X, never
# older. glibc, libGL/glvnd and the X/Wayland client libs stay on the host per
# the excludelist (bundling driver-coupled GL libs crashes elsewhere).
#
# PyInstaller bundles Python + Qt under usr/bin/_internal but leaves the Qt xcb
# platform plugin's libxcb-cursor/icccm/util + fontconfig/freetype closure to the
# host (the same set the .deb declares as Depends). The .deb gets these from the
# host; the AppImage can't, so we vendor them into usr/lib.
#
# Usage (from the repo root):
#   pyinstaller packaging/pyinstaller/dough.spec --noconfirm
#   bash packaging/appimage/build_appimage.sh <version>
#
# Output: dist/dough-<version>-x86_64.AppImage  (+ .AppImage.zsync)
set -euo pipefail

VERSION="${1:?usage: build_appimage.sh <version>}"
ROOT="$(git rev-parse --show-toplevel)"
APP_ID="io.github.wolfgangwarehaus.dough"
BUNDLE="$ROOT/dist/dough"
APPDIR="$ROOT/dist/dough.AppDir"

[ -x "$BUNDLE/dough" ] || {
  echo "error: $BUNDLE/dough missing — run pyinstaller first." >&2
  exit 1
}

# ── Stage the AppDir: the frozen onedir goes under usr/bin ────────────────────
rm -rf "$APPDIR"
mkdir -p "$APPDIR/usr/bin" "$APPDIR/usr/lib" \
         "$APPDIR/usr/share/metainfo" \
         "$APPDIR/usr/share/icons/hicolor/scalable/apps"
cp -a "$BUNDLE/." "$APPDIR/usr/bin/"   # dough binary + _internal/

# ── Vendor the system shared-lib closure the frozen app + Qt plugins need ─────
# EXCLUDE the AppImage excludelist (glibc, the C++ runtime, GL/glvnd, base X/xcb,
# wayland) — those MUST come from the user's host so the GL stack matches their
# driver and forward-compat holds.
is_excluded() {
  case "$1" in
    libc.so.*|libm.so.*|libdl.so.*|libpthread.so.*|librt.so.*|libresolv.so.*|\
    ld-linux*.so.*|libstdc++.so.*|libgcc_s.so.*|\
    libGL.so.*|libEGL.so.*|libGLdispatch.so.*|libGLX.so.*|libOpenGL.so.*|libdrm.so.*|\
    libX11.so.*|libX11-xcb.so.*|libxcb.so.*|libwayland-*.so.*) return 0 ;;
    *) return 1 ;;
  esac
}

# ldd a binary (with _internal on the path so the bundled Qt libs resolve and ldd
# recurses into THEIR deps) and copy each system-resolved dep that is neither
# excludelisted nor already inside the bundle.
vendor_closure() {
  LD_LIBRARY_PATH="$APPDIR/usr/bin/_internal" ldd "$1" 2>/dev/null \
    | awk '/=> \// {print $3}' | while read -r path; do
    [ -e "$path" ] || continue
    case "$path" in "$APPDIR"/*) continue ;; esac   # already bundled in _internal
    bn="$(basename "$path")"
    is_excluded "$bn" && continue
    [ -e "$APPDIR/usr/lib/$bn" ] && continue
    cp -Ln "$path" "$APPDIR/usr/lib/$bn" && echo "  + $bn"
  done
}

# The Qt xcb platform plugin's closure — libxcb-cursor0 (Qt 6.5+ hard-needs it,
# the #1 "could not load the Qt platform plugin xcb" failure) + the xcb-util /
# fontconfig / freetype libs PyInstaller leaves to the host.
echo "Vendoring the Qt xcb platform-plugin closure:"
XCB_PLUGIN="$(find "$APPDIR/usr/bin/_internal" -name 'libqxcb.so' -print -quit 2>/dev/null)"
if [ -n "$XCB_PLUGIN" ]; then
  vendor_closure "$XCB_PLUGIN"
else
  echo "  ! libqxcb.so not found in the bundle — the AppImage may not start on X11" >&2
fi

# The frozen launcher itself, to catch anything else it pulls from the host.
vendor_closure "$APPDIR/usr/bin/dough"

# ── AppRun: bundled libs on the loader path, then exec the frozen app ─────────
cat > "$APPDIR/AppRun" <<'EOF'
#!/bin/bash
HERE="$(dirname "$(readlink -f "${0}")")"
export LD_LIBRARY_PATH="$HERE/usr/lib:$HERE/usr/bin/_internal${LD_LIBRARY_PATH:+:$LD_LIBRARY_PATH}"
exec "$HERE/usr/bin/dough" "$@"
EOF
chmod +x "$APPDIR/AppRun"

# ── Desktop entry + icon + metainfo (appimagetool reads the AppDir-root pair) ──
cp "$ROOT/packaging/$APP_ID.desktop"      "$APPDIR/$APP_ID.desktop"
cp "$ROOT/packaging/$APP_ID.metainfo.xml" "$APPDIR/usr/share/metainfo/"
ICON="$ROOT/dough/assets/dough.svg"
cp "$ICON" "$APPDIR/$APP_ID.svg"          # root icon (matches Icon= key)
cp "$ICON" "$APPDIR/usr/share/icons/hicolor/scalable/apps/$APP_ID.svg"
# .DirIcon: file-manager thumbnailers want a PNG (most ignore an SVG .DirIcon).
# Rasterize a 256px PNG if a converter is present; fall back to the SVG otherwise.
if command -v rsvg-convert >/dev/null 2>&1; then
  rsvg-convert -w 256 -h 256 "$ICON" -o "$APPDIR/.DirIcon"
elif command -v inkscape >/dev/null 2>&1; then
  inkscape "$ICON" -w 256 -h 256 -o "$APPDIR/.DirIcon" >/dev/null 2>&1
elif command -v magick >/dev/null 2>&1; then
  magick -background none -size 256x256 "$ICON" "$APPDIR/.DirIcon"
else
  echo "  ! no SVG rasterizer (rsvg-convert/inkscape/magick) — .DirIcon falls back to SVG" >&2
  cp "$ICON" "$APPDIR/.DirIcon"
fi

# ── appimagetool: static type-2 runtime → the AppImage needs NO libfuse on the
#    user's machine. appimagetool itself needs no FUSE on CI with EXTRACT_AND_RUN.
TOOL="${APPIMAGETOOL:-$ROOT/dist/appimagetool}"
if [ ! -x "$TOOL" ]; then
  echo "Fetching appimagetool (continuous, static runtime)…"
  curl -fsSL -o "$TOOL" \
    "https://github.com/AppImage/appimagetool/releases/download/continuous/appimagetool-x86_64.AppImage"
  chmod +x "$TOOL"
fi

OUT="$ROOT/dist/dough-${VERSION}-x86_64.AppImage"
export APPIMAGE_EXTRACT_AND_RUN=1
# -u embeds gh-releases zsync update-info so AppImageUpdate can do delta updates;
# appimagetool also emits the companion .AppImage.zsync next to the output.
ARCH=x86_64 "$TOOL" \
  --updateinformation "gh-releases-zsync|wolfgangwarehaus|dough|latest|dough-*-x86_64.AppImage.zsync" \
  "$APPDIR" "$OUT"

echo "✓ built $OUT"
ls -lh "$OUT" "${OUT}.zsync" 2>/dev/null || true
