#!/usr/bin/env bash
# Smoke-test the AppImage in a CLEAN container that has NEITHER the Qt xcb libs —
# the only way to prove the AppImage truly self-contains them (an in-runner boot
# has the build host's libs, so it can't). GENERATED by `dough bake` — edit the
# template, never this file.
#   for img in ubuntu:24.04 debian:stable; do
#     docker run --rm -v "$PWD:/src:ro" "$img" bash /src/packaging/appimage/smoke_test_appimage.sh
#   done
set -euo pipefail

apt-get update -qq
# A real X server + the GL baseline (driver-coupled, on the AppImage excludelist →
# host-provided). DELIBERATELY NOT libxcb-cursor0 / the xcb-util / fontconfig
# closure: those MUST come from inside the AppImage or this test is meaningless.
DEBIAN_FRONTEND=noninteractive apt-get install -y -qq xvfb libgl1 libegl1 >/dev/null

shopt -s nullglob
_imgs=(/src/dist/dough-*-x86_64.AppImage)
APPIMAGE="${_imgs[0]:-}"
test -n "$APPIMAGE" || { echo "FAIL: no AppImage in /src/dist"; exit 1; }

export APPIMAGE_EXTRACT_AND_RUN=1   # no FUSE in a container → extract-and-run
cp "$APPIMAGE" /tmp/app.AppImage
chmod +x /tmp/app.AppImage

echo "Booting the AppImage under Xvfb (xcb) in a clean container ($(sed -n 's/^PRETTY_NAME=//p' /etc/os-release))…"
set +e
QT_DEBUG_PLUGINS=1 QT_QPA_PLATFORM=xcb xvfb-run -a timeout 25 /tmp/app.AppImage >/tmp/appimage-boot.log 2>&1
rc=$?
set -e
if [ "$rc" != 124 ] && [ "$rc" != 0 ]; then
  echo "FAIL: the AppImage did not boot cleanly (rc=$rc) — a bundled lib is missing."
  grep -iE "cannot open shared object|Cannot load library|undefined symbol" /tmp/appimage-boot.log \
    || echo "(no 'cannot open shared object' line — inspect the full log)"
  tail -30 /tmp/appimage-boot.log
  exit 1
fi
echo "OK: AppImage boots self-contained under Xvfb (rc=$rc) — the xcb closure is bundled"
echo "appimage smoke test passed"
