# Homebrew cask for dough. GENERATED by `dough bake` — the INITIAL
# cask to seed your tap (homebrew-<tap>); macos.yml's bump action maintains the
# version + sha256 thereafter (docs/BAKING.md §5). Committed form is version-free.
cask "dough" do
  version "0.0.0"
  sha256 :no_check

  url "https://github.com/wolfgangwarehaus/dough/releases/download/v#{version}/dough-#{version}-macos.dmg"
  name "dough"
  desc "A frosted, cross-platform PySide6 app base"
  homepage "https://github.com/wolfgangwarehaus/dough"

  app "dough.app"

  zap trash: [
    "~/Library/Preferences/com.wolfgangwarehaus.dough.plist",
    "~/Library/Application Support/dough",
    "~/Library/Saved Application State/com.wolfgangwarehaus.dough.savedState",
  ]
end
