# Homebrew cask for tracker keeper. GENERATED by `trackerkeeper bake` — the INITIAL
# cask to seed your tap (homebrew-<tap>); macos.yml's bump action maintains the
# version + sha256 thereafter (docs/BAKING.md §5). Committed form is version-free.
cask "trackerkeeper" do
  version "0.0.0"
  # universal2 → ONE fat .dmg serves both Apple Silicon and Intel, so a single
  # sha256 + url is correct. The per-arch fallback (a fork that ships two native
  # -macos-<arch>.dmg files) replaces these with on_arm/on_intel two-sha blocks
  # + two urls — see the spec's target_arch note.
  sha256 :no_check

  url "https://github.com/wolfgangwarehaus/trackerkeeper/releases/download/v#{version}/trackerkeeper-#{version}-macos.dmg"
  name "tracker keeper"
  desc "One dashboard for software & firmware updates across everything you own"
  homepage "https://github.com/wolfgangwarehaus/trackerkeeper"

  app "trackerkeeper.app"

  zap trash: [
    "~/Library/Preferences/com.wolfgangwarehaus.trackerkeeper.plist",
    "~/Library/Application Support/tracker keeper",
    "~/Library/Saved Application State/com.wolfgangwarehaus.trackerkeeper.savedState",
  ]
end
