# -*- mode: python ; coding: utf-8 -*-
# PyInstaller onedir spec for dough (Linux). GENERATED by `dough
# bake` from [tool.dough.metadata] — edit the template, never this file.
#
# Run from the repo root:  pyinstaller packaging/pyinstaller/dough.spec --noconfirm
# Output: dist/dough/  (the onedir the deb + AppImage builders consume).
import os

from PyInstaller.utils.hooks import collect_data_files

# SPECPATH is the spec's own directory (packaging/pyinstaller); ROOT is the repo.
HERE = SPECPATH
ROOT = os.path.dirname(os.path.dirname(HERE))

# Ship the brand SVG (resolved at runtime via importlib.resources) + the license.
datas = collect_data_files("dough", includes=["assets/*.svg"])
datas += [(os.path.join(ROOT, "LICENSE"), ".")]

a = Analysis(
    [os.path.join(HERE, "launch.py")],
    pathex=[ROOT],
    binaries=[],
    datas=datas,
    hiddenimports=[],
    hookspath=[],
    runtime_hooks=[],
    excludes=["tkinter"],
    noarchive=False,
)
pyz = PYZ(a.pure)

exe = EXE(
    pyz,
    a.scripts,
    [],
    exclude_binaries=True,
    name="dough",
    debug=False,
    strip=False,
    upx=False,
    console=False,
)
coll = COLLECT(
    exe,
    a.binaries,
    a.datas,
    strip=False,
    upx=False,
    name="dough",
)
