# -*- mode: python ; coding: utf-8 -*-
# PyInstaller onedir spec for dough. GENERATED by `dough bake` from
# [tool.dough.metadata] — edit the template, never this file. One spec for both
# frozen targets:
#   Linux   → the onedir the .deb stages under /opt/dough + the AppImage wraps.
#   Windows → the windowed onedir Inno Setup / the portable zip wrap, with the
#             generated .ico + version_info.txt (built by release.yml before this).
#
# Run from the repo root:  pyinstaller packaging/pyinstaller/dough.spec --noconfirm
import os
import sys

from PyInstaller.utils.hooks import collect_data_files

# SPECPATH is the spec's own directory (packaging/pyinstaller); ROOT is the repo.
HERE = SPECPATH
ROOT = os.path.dirname(os.path.dirname(HERE))

# Ship the brand SVG (resolved at runtime via importlib.resources) + the license.
datas = collect_data_files("dough", includes=["assets/*.svg"])
datas += [(os.path.join(ROOT, "LICENSE"), ".")]

a = Analysis(
    [os.path.join(HERE, "launch.py")],
    pathex=[ROOT],
    binaries=[],
    datas=datas,
    hiddenimports=[],
    hookspath=[],
    runtime_hooks=[],
    excludes=[
        # Heavy Qt modules the chrome never imports — keeps the bundle lean. A
        # fork that uses any of these removes it from this list.
        "tkinter",
        "PySide6.QtWebEngineCore",
        "PySide6.QtWebEngineWidgets",
        "PySide6.QtQuick",
        "PySide6.QtQml",
        "PySide6.Qt3DCore",
        "PySide6.QtCharts",
        "PySide6.QtDataVisualization",
        "PySide6.QtPdf",
    ],
    noarchive=False,
)
pyz = PYZ(a.pure)

# Windows: stamp the generated icon + VSVersionInfo when release.yml produced them.
exe_kwargs = {}
if sys.platform == "win32":
    _ico = os.path.join(ROOT, "packaging", "windows", "dough.ico")
    if os.path.exists(_ico):
        exe_kwargs["icon"] = _ico
    _ver = os.path.join(ROOT, "packaging", "windows", "version_info.txt")
    if os.path.exists(_ver):
        exe_kwargs["version"] = _ver
# macOS: build a SINGLE universal2 (arm64 + x86_64) binary so ONE .dmg + one
# Homebrew cask serve both Apple Silicon and Intel Macs. This needs a
# universal2 wheel for every compiled dependency (PySide6 ships them). The
# PER-ARCH FALLBACK — two native builds → two -macos-<arch>.dmg files with
# on_arm/on_intel sha256 blocks in the cask — is for a fork whose deps are
# thin-only (e.g. numpy/cffi with no universal2 wheel), where --target-arch
# universal2 aborts on the thin binaries.
elif sys.platform == "darwin":
    exe_kwargs["target_arch"] = "universal2"

exe = EXE(
    pyz,
    a.scripts,
    [],
    exclude_binaries=True,
    name="dough",
    debug=False,
    strip=False,
    upx=False,
    console=False,  # GUI app — no console window on Windows
    **exe_kwargs,
)
coll = COLLECT(
    exe,
    a.binaries,
    a.datas,
    strip=False,
    upx=False,
    name="dough",
)

# macOS: wrap the onedir in a .app bundle (the .dmg + Homebrew cask ship this).
# The .icns is generated from the brand SVG by macos.yml; absent it, PyInstaller
# falls back to its default icon.
if sys.platform == "darwin":
    _icns = os.path.join(ROOT, "packaging", "macos", "dough.icns")
    app = BUNDLE(
        coll,
        name="dough.app",  # match macos.yml + the cask; no spaces for the shell
        icon=_icns if os.path.exists(_icns) else None,
        bundle_identifier="com.wolfgangwarehaus.dough",
        info_plist={
            "CFBundleShortVersionString": "0.0.0",
            "CFBundleVersion": "0.0.0",
            "NSHighResolutionCapable": True,
            # CI-OVERWRITTEN PLACEHOLDER — macos.yml pins the bundle's REAL macOS
            # floor into Contents/Info.plist after freezing, via PlistBuddy
            #   "Set :LSMinimumSystemVersion <floor>"
            # (the honest-floor pin), so LaunchServices shows an honest "needs
            # macOS X" instead of a silent dock-bounce on an older system. 11.0
            # (Big Sur) is the universal2 baseline and the default a local,
            # un-pinned build ships.
            "LSMinimumSystemVersion": "11.0",
            # A fork maps its freedesktop categories to the right UTI here.
            "LSApplicationCategoryType": "public.app-category.developer-tools",
        },
    )

