"""PyInstaller entry shim for the frozen bundle. GENERATED by `dough bake`.

A bare module that calls the configured entry point (dough.app:main). The
freeze targets this file (not ``-m dough``) so PyInstaller's analysis
has a concrete script to start from.
"""
from dough.app import main

if __name__ == "__main__":
    main()
