"""PyInstaller entry shim for the frozen bundle. GENERATED by `trackerkeeper bake`.

A bare module that calls the configured entry point (trackerkeeper.app:main). The
freeze targets this file (not ``-m trackerkeeper``) so PyInstaller's analysis
has a concrete script to start from.
"""
from trackerkeeper.app import main

if __name__ == "__main__":
    main()
